### ISSUE TITLE
Fix Text Selection Color and Readability

### ISSUE THREAD

**Issue by weir1** [weir1/moin-portfolio-2024#17]
## Issue Description
Text selection colors are not properly configured, making selected text difficult to read. This affects user experience and accessibility across the website.

### Current Issues
1. Poor contrast in text selection
2. Inconsistent selection colors
3. Readability problems when text is selected
4. Accessibility concerns

### Required Changes
1. **Update Selection Colors**
   - Configure proper selection background color
   - Ensure sufficient contrast with selected text
   - Maintain brand consistency
   - Support both light and dark themes

2. **Technical Implementation**
   ```css
   /* Example implementation in theme */
   ::selection {
     background-color: ${theme.palette.primary.main}; /* Brand color with proper opacity */
     color: ${theme.palette.primary.contrastText}; /* Ensure readability */
     text-shadow: none; /* Remove any interfering effects */
   }
   ```

3. **Theme Integration**
   - Add selection colors to theme configuration
   - Implement dark/light mode variants
   - Ensure consistent application across components
   - Add proper CSS specificity handling

### Accessibility Requirements
- Meet WCAG 2.1 contrast requirements
- Test with screen readers
- Verify readability in all color modes
- Support high contrast mode

### Testing Checklist
- [ ] Test in light mode
- [ ] Test in dark mode
- [ ] Verify all text components
- [ ] Check custom components
- [ ] Validate contrast ratios
- [ ] Test with assistive technologies

### Acceptance Criteria
- [ ] Selected text is clearly readable
- [ ] Consistent behavior across all sections
- [ ] Proper contrast ratios maintained
- [ ] Works in both light/dark modes
- [ ] Meets accessibility standards
- [ ] No conflicts with existing styles
